import { Box, Grid, Typography, Button } from '@mui/material';
import Image from 'next/image';
import Head from 'next/head';
import React from 'react';
import HeaderInstitucional from '../components/ui/header/Header';
// import styles from '../styles/components/Ajuda.module.css';
import NextLink from 'next/link';
import ajudaArara from '../images/ajuda-arara.png';
import logoGeoIA from '../public/logo.ico';
import call from '../images/call.svg';
import mail from '../images/mail.svg';
import form from '../images/form.svg';
import FooterInstitucional from '../components/ui/footer/footer';

const Ajuda = () => {
  return (
    <div>
      <Head>
        <title>GeoIa WebGis</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="logoGeoIA" href="../public/logo.ico" />
      </Head>
      <HeaderInstitucional />
      <Box
        sx={{
          height: 700,
          margin: '2em 0',
          paddingRight: '40em',
        }}
      >
        <Grid container alignItems="center" justifyContent="space-between">
          <Grid item>
            <Image src={ajudaArara} alt="ajudaArara" />
          </Grid>
          <Grid item>
            <h2>Como podemos te ajudar?</h2>
            <h3>Tópicos frequentes</h3>
            <Typography variant="h4" sx={{ color: 'white' }}>
              Lorem ipsum dolor sit amet, consectetur.
            </Typography>
          </Grid>
        </Grid>
      </Box>
      <Box
        sx={{
          height: 700,
          margin: '2em 0',
          paddingRight: '40em',
          justifyContent: 'center',
          display: 'flex',
        }}
      >
        <Grid container alignItems="center" justifyContent="space-between">
          <Grid>
            <div>
              <a>
                <Image src={mail} alt="mail" width={170} height={150} />
                <h2>E-mail</h2>
                <p>geoiawebgis@gmail.com</p>
              </a>
            </div>
          </Grid>
          <Grid item>
            <div>
              <a>
                <Image src={call} alt="call" width={170} height={150} />
                <h2>Telefone</h2>
                <p>(67)99999-9999</p>
              </a>
            </div>
          </Grid>
          <Grid item>
            <div>
              <a>
                <Image src={form} alt="form" width={150} height={150} />
                <h2>Formulário</h2>
                <p>Envie-nos sua dúvida por meio do formulário de contato.</p>
              </a>
            </div>
          </Grid>
        </Grid>
      </Box>

      <footer>
        <FooterInstitucional />
      </footer>
    </div>
  );
};

export default Ajuda;
